server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
    path: /error
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: debug